<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Game</RootNamespace>
        <TargetFramework>net9.0-android</TargetFramework>
        <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
        <AndroidApplication>true</AndroidApplication>
        <ApplicationId>com.candy.SurvivalcraftAPI1_8</ApplicationId>
        <AssemblyName>Launch_android</AssemblyName>
        <Nullable>enable</Nullable>
        <Product>Survivalcraft</Product>
        <Version>2.4.0.0</Version>
        <NeutralLanguage>zh-CN</NeutralLanguage>
        <AndroidStoreUncompressedFileExtensions>.dll</AndroidStoreUncompressedFileExtensions>
        <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
        <AndroidPackageFormat>apk</AndroidPackageFormat>
        <!--签名-->
        <AndroidKeyStore>true</AndroidKeyStore>
        <AndroidSigningKeyAlias>androiddebugkey</AndroidSigningKeyAlias>
        <AndroidSigningKeyStore>Signing.keystore</AndroidSigningKeyStore>
        <AndroidSigningStorePass>android</AndroidSigningStorePass>
        <AndroidSigningKeyPass>android</AndroidSigningKeyPass>
        <!--优化-->
        <LinkAll>true</LinkAll>
        <PublishTrimmed>false</PublishTrimmed><!--切记不要修改，如果修改会导致运行时不完整-->
        <TrimMode>partial</TrimMode>
        <AndroidDexTool>d8</AndroidDexTool>
        <AndroidEnableSGenConcurrent>false</AndroidEnableSGenConcurrent>
        <AndroidLinkMode>None</AndroidLinkMode>
        <AndroidLintEnabled>false</AndroidLintEnabled>
        <AndroidStripILAfterAOT>true</AndroidStripILAfterAOT>
        <AndroidUseInterpreter>false</AndroidUseInterpreter>
        <EnableLLVM>true</EnableLLVM>
        <RunAOTCompilation>false</RunAOTCompilation>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugType>none</DebugType>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <AndroidAsset Include="..\Engine\Resources\Lit.psh" Link="Assets\Lit.psh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\Lit.vsh" Link="Assets\Lit.vsh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\UnLit.psh" Link="Assets\Unlit.psh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\UnLit.vsh" Link="Assets\Unlit.vsh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\Debugfont.png" Link="Assets\Debugfont.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\Debugfont.lst" Link="Assets\Debugfont.lst">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Survivalcraft\Content.zip" Link="Assets\Content.zip">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Survivalcraft_android\A_Survivalcraft.csproj" />
    </ItemGroup>
</Project>