<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Game</RootNamespace>
        <AssemblyName>Survivalcraft</AssemblyName>
        <TargetFramework>net9.0-android</TargetFramework>
        <ApplicationVersion>2.4.0.0</ApplicationVersion>
        <AssemblyVersion>2.4.0.0</AssemblyVersion>
        <FileVersion>2.4.0.0</FileVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
        <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugType>none</DebugType>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\EntitySystem\EntitySystem.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Jint" Version="4.4.1" />
        <PackageReference Include="NAudio.Flac.Unknown.Mod" Version="1.0.3" />
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Survivalcraft.Windows\**\*.cs" Exclude="..\Survivalcraft.Windows\obj\**\*.cs"/>
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="..\Survivalcraft.Windows\init.js">
        <Link>init.js</Link>
      </EmbeddedResource>
    </ItemGroup>
</Project>